<?php


namespace App\Twig;


use App\Repository\UserRepository;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class AppExtension extends AbstractExtension
{
   public function  getFunctions()
   {
      // return parent::getFunctions(); // TODO: Change the autogenerated stub

       return array(
           new TwigFunction('find', array($this, 'find')),
           new TwigFunction('phoneFormat', array($this, 'phoneFormat')),
       );
   }

   public function __construct(private  UserRepository $userRepository)
   {
   }

    public  function  find($id)
   {
          return $this->userRepository->find($id);
   }

   public  function  phoneFormat($no)
   {
         return '******'. substr($no, -4);
   }
}